const U='https://hlijqqugqglybrutooak.supabase.co',K='sb_publishable_OKCjPi6GZ7n3MLfcMyjBtw_3gHF19BI';let sb,user=null,studyHours=0,state={doneRes:{},open:{1:true},branch:'red'};const KEY='cyber_roadmap_progress_v3',STUDY='cyber_roadmap_study_hours_v1';
const mainStages=[
{id:1,title:'أساسيات علوم الحاسب',sub:'Computer Science',resources:[['CS50 Harvard','Nouvil','https://nouvil.net/courses/cs50-2022/'],['CompTIA A+','Sameh Ramadan','https://www.youtube.com/playlist?list=PLH-n8YK76vIiDdOMRB-ylvns-_8Zl1euV']]},
{id:2,title:'الشبكات',sub:'Network',resources:[['CompTIA Network+','Sameh Ramadan','https://www.youtube.com/playlist?list=PLH-n8YK76vIiuIZoWvHL7AvtrDV7hR3He']]},
{id:3,title:'لينكس',sub:'Linux',resources:[['Linux','Hacktivity-AR','https://www.youtube.com/playlist?list=PLDxVq3TlR9y2sMXaL_yLp-r6pUpevgC-w'],['Linux System Administration','Arab Linux Community','https://www.youtube.com/playlist?list=PLy1Fx2HfcmWBpD_PI4AQpjeDK5-5q6TG7']]},
{id:4,title:'أوامر الويندوز',sub:'Windows Commands',resources:[['PowerShell','تقنية دوت نت','https://www.youtube.com/watch?v=6GPZthxEKU0']]},
{id:5,title:'البرمجة',sub:'Programming',resources:[['HTML و CSS','Yehia Tech','https://www.youtube.com/watch?v=Pwatx1n1Ws0'],['JavaScript','Elzero Web School','https://www.youtube.com/playlist?list=PLDoPjvoNmBAx3kiplQR_oeDqLDBUDYwVv'],['PHP','Nour Homsi','https://www.youtube.com/watch?v=pszZMzI9a7A'],['MySQL','كورسات في البرمجة','https://www.youtube.com/watch?v=N-WPYk417yE'],['CRUD','Nour Homsi','https://www.youtube.com/watch?v=6hgBFDTTwEk'],['Secure Web App','Elzero Web School','https://www.youtube.com/playlist?list=PLDoPjvoNmBAypWmEHEy3awR6Ek9sUe5ZS'],['Python','Abdelrahman Gamal','https://www.youtube.com/playlist?list=PLknwEmKsW8OsG8dnisr_-2WGyx7lpgGEE']]},
{id:6,title:'أساسيات الأمن السيبراني',sub:'Security Basics',resources:[['Security+ SY0-601 Prep','Netriders Academy - Ahmed Sultan','https://netriders.academy/courses/security/']]},
{id:7,title:'اختبار الاختراق',sub:'Penetration Testing',resources:[['eJPTv1 Prep','Netriders Academy - Ahmed Sultan','https://netriders.academy/courses/penetration-testing-student']]},
{id:8,title:'اختبار اختراق تطبيقات الويب',sub:'WAPT',resources:[['Web App Basics + Burp Suite + ZAProxy','GenTiL Security','https://www.youtube.com/watch?v=MFanMkTGJSo'],['WAPT Course','GenTiL Security','https://www.youtube.com/playlist?list=PLX621demLUSaA7ngeN7UfVzYJihHnEfv0']]}];
const red=[{id:'r1',title:'الأمن الهجومي',sub:'Offensive Security',resources:[['OSCP','Nakerah Network','https://www.youtube.com/playlist?list=PL_yseowcuqYJc7wXtGIsshYp1B_W0M-ZK']]}];
const blue=[{id:'b1',title:'الاستجابة للحوادث',sub:'Incident Response',resources:[['eCIR Prep','Netriders Academy - Ahmed Sultan','https://netriders.academy/courses/incident-response']]},{id:'b2',title:'أمن الشبكات',sub:'Network Security',resources:[['CCNP Security SCOR','Netriders Academy - Ahmed Sultan','https://netriders.academy/courses/scor']]}];
const hours={};mainStages.forEach(s=>s.resources.forEach((r,i)=>hours[s.id+':'+i]=s.id===1&&i===0?50:20));
try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');state=Object.assign(state,x);state.doneRes=state.doneRes||{};state.open=state.open||{1:true};studyHours=Number(localStorage.getItem(STUDY)||0)}catch(e){}const $=id=>document.getElementById(id);const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(STUDY,String(studyHours))};
function message(t){const m=$('msg');if(m)m.textContent=t}
async function sync(){if(!user)return;const now=new Date().toISOString();const rows=Object.entries(state.doneRes).map(([course_id,v])=>({user_id:user.id,course_id,completed:!!v,completed_at:v?now:null,updated_at:now}));if(rows.length){const r=await sb.from('progress').upsert(rows,{onConflict:'user_id,course_id'});if(r.error)throw r.error}const p=await sb.from('profiles').upsert({id:user.id,study_hours:studyHours||2,updated_at:now},{onConflict:'id'});if(p.error)throw p.error}
async function load(){const p=await sb.from('profiles').select('study_hours').eq('id',user.id).maybeSingle();if(p.error)throw p.error;const q=await sb.from('progress').select('course_id,completed').eq('user_id',user.id);if(q.error)throw q.error;const local=Object.entries(state.doneRes).filter(([,v])=>v);if(q.data.length)q.data.forEach(x=>state.doneRes[x.course_id]=!!x.completed);else if(local.length){const rows=local.map(([course_id])=>({user_id:user.id,course_id,completed:true,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}));const r=await sb.from('progress').upsert(rows,{onConflict:'user_id,course_id'});if(r.error)throw r.error}if(p.data?.study_hours!=null)studyHours=Number(p.data.study_hours);else {studyHours=studyHours||2;await sync()}save()}
function auth(mode='login'){document.body.innerHTML=`<main class="center"><section class="auth"><div class="logo">⌁</div><h1>CYBER SECURITY ROADMAP</h1><p>${mode==='login'?'سجّل الدخول لاستعادة تقدمك من أي جهاز.':'أنشئ حسابك واحفظ تقدمك وخطة المذاكرة على السحابة.'}</p><input id="email" type="email" autocomplete="email" placeholder="البريد الإلكتروني"><input id="pass" type="password" autocomplete="current-password" placeholder="كلمة المرور — 6 أحرف على الأقل"><div id="msg"></div><button id="go">${mode==='login'?'تسجيل الدخول':'إنشاء الحساب'}</button><button class="link" id="swap">${mode==='login'?'ليس لديك حساب؟ إنشاء حساب':'عندك حساب؟ تسجيل الدخول'}</button></section></main>`;$('go').onclick=async()=>{const b=$('go'),email=$('email').value.trim(),password=$('pass').value;if(!email||password.length<6)return message('اكتب إيميل صحيح وكلمة مرور 6 أحرف على الأقل.');b.disabled=true;b.textContent='جاري تسجيل الدخول…';try{const r=mode==='login'?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password});if(r.error)throw r.error;if(mode==='signup'){message('تم إنشاء الحساب. لو ظهر طلب تأكيد الإيميل، أكّده ثم سجّل الدخول.');b.disabled=false;b.textContent='إنشاء الحساب';return}if(!r.data.session)throw new Error('تم التحقق من الحساب لكن لم يتم إنشاء جلسة. لو كان تأكيد الإيميل مطلوبًا، أكّد الإيميل أولًا.');user=r.data.user;await load();render()}catch(e){console.error(e);message(e.message||'تعذر تسجيل الدخول.');b.disabled=false;b.textContent='تسجيل الدخول'}};$('swap').onclick=()=>auth(mode==='login'?'signup':'login')}
function study(){document.body.innerHTML=`<main class="center"><section class="auth"><div class="logo">⏱</div><h1>خطة المذاكرة اليومية</h1><p>اختار عدد الساعات التي تقدر تذاكرها يوميًا. هتتحفظ في حسابك.</p><div class="hours">${[1,2,3,4,5,6].map(h=>`<button data-h="${h}">${h} ساعة</button>`).join('')}</div></section></main>`;document.querySelectorAll('[data-h]').forEach(b=>b.onclick=async()=>{studyHours=+b.dataset.h;save();try{await sync();render()}catch(e){message(e.message||'تعذر حفظ خطة المذاكرة.')}})}
function done(s){return s.resources.filter((r,i)=>state.doneRes[s.id+':'+i]).length}function stage(s,ac=''){const d=done(s),t=s.resources.length,o=!!state.open[s.id];return `<article class="stage ${ac}"><button class="stagehead" data-open="${s.id}"><span><b>${s.title}</b><small>${s.sub} · ${d}/${t}</small></span><i>${o?'−':'+'}</i></button>${o?`<div class="resources">${s.resources.map((r,i)=>{const k=s.id+':'+i,on=!!state.doneRes[k];return `<div class="res"><button class="check ${on?'on':''}" data-res="${k}">${on?'✓':''}</button><a href="${r[2]}" target="_blank" rel="noreferrer"><strong>${r[0]}</strong><small>${r[1]}</small><em>⏱ تقديريًا: ${Math.ceil((hours[k]||20)/Math.max(1,studyHours))} يوم · ${studyHours} ساعة/يوم</em></a></div>`}).join('')}</div>`:''}</article>`}
function render(){const n=mainStages.reduce((a,s)=>a+done(s),0),t=mainStages.reduce((a,s)=>a+s.resources.length,0),p=Math.round(n/t*100),branch=state.branch==='red'?red:blue;document.body.innerHTML=`<main id="app"><header><small>MR. KAREEM ELSHORBAGY / ROBOT</small><h1>CYBER SECURITY ROADMAP — FREE ARABIC COURSES</h1><div class="account"><span>👤 ${user.email}</span><button id="hours">⏱ ${studyHours} ساعة</button><button id="logout">خروج</button></div></header><section class="progress"><div class="ring">${p}%</div><div><b>التقدم في المسار الأساسي</b><small>${n}/${t} مصدر مكتمل</small></div></section><div class="list">${mainStages.map(s=>stage(s)).join('')}</div><div class="banner">⚡ أنت الآن صائد ثغرات محترف</div><nav><button class="${state.branch==='red'?'active red':''}" data-branch="red">⚡ Red Team</button><button class="${state.branch==='blue'?'active blue':''}" data-branch="blue">🔒 Blue Team</button></nav><div class="list">${branch.map(s=>stage(s,state.branch==='red'?'red':'blue')).join('')}</div><footer>MR. Kareem Elshorbagy / ROBOT</footer></main>`;document.querySelectorAll('[data-res]').forEach(b=>b.onclick=async()=>{const k=b.dataset.res;state.doneRes[k]=!state.doneRes[k];save();try{await sync();render()}catch(e){console.error(e)}});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const k=isNaN(b.dataset.open)?b.dataset.open:+b.dataset.open;state.open[k]=!state.open[k];save();render()});document.querySelectorAll('[data-branch]').forEach(b=>b.onclick=()=>{state.branch=b.dataset.branch;save();render()});$('logout').onclick=async()=>{await sb.auth.signOut();user=null;auth()};$('hours').onclick=study}
async function boot(){try{sb=window.supabase.createClient(U,K);const r=await sb.auth.getSession();user=r.data.session?.user||null;if(user){await load();if(!studyHours)study();else render()}else auth();sb.auth.onAuthStateChange((e,s)=>{if(e==='SIGNED_OUT'){user=null;auth()}})}catch(e){console.error(e);document.body.innerHTML='<main class="center"><section class="auth"><h1>CYBER SECURITY ROADMAP</h1><p>تعذر تشغيل تسجيل الدخول. أعد تحميل الصفحة.</p><button onclick="location.reload()">إعادة المحاولة</button></section></main>'}}
if(window.supabase)boot();else{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=boot;s.onerror=()=>message('تعذر تحميل خدمة الحسابات.');document.head.appendChild(s)}